CONFIG_PINCTRL=y
CONFIG_GPIO=y
CONFIG_PWM=y

CONFIG_LORA=y
CONFIG_LORA_SX127X=y

CONFIG_SPI=y

CONFIG_CBPRINTF_FP_SUPPORT=y


# Enables deep sleep modes
CONFIG_PM=y                   # Enable power management
CONFIG_PM_DEVICE=y            # For device power management
CONFIG_PM_DEVICE_RUNTIME=y
CONFIG_PM_DEVICE_SYSTEM_MANAGED=y
CONFIG_TICKLESS_KERNEL=y
CONFIG_STM32_LPTIM_TIMER=y

CONFIG_COUNTER=y

# for the 1-wire temperature sensor
CONFIG_SENSOR=y
CONFIG_W1=y

CONFIG_ADC=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3